In [1]:
# Dependencies and Setup
import pandas as pd
import gmaps
import requests


# Import API key
from api_keys import gkey

In [2]:
gmaps.configure(api_key=gkey)

In [3]:
jhcounty_cases = pd.read_csv('Cases by day by county.csv')
jhcounty_cases

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,6/8/2020,6/9/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020
0,16,AS,ASM,16,60.0,NaN,American Samoa,US,-14.271000,-170.132000,...,0,0,0,0,0,0,0,0,0,0
1,316,GU,GUM,316,66.0,NaN,Guam,US,13.444300,144.793700,...,179,180,180,183,183,183,183,185,186,188
2,580,MP,MNP,580,69.0,NaN,Northern Mariana Islands,US,15.097900,145.673900,...,28,30,30,30,30,30,30,30,30,30
3,630,PR,PRI,630,72.0,NaN,Puerto Rico,US,18.220800,-66.590100,...,5046,5185,5329,5352,5536,5690,5811,5890,5951,6003
4,850,VI,VIR,850,78.0,NaN,Virgin Islands,US,18.335800,-64.896300,...,71,71,72,72,72,72,72,72,72,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3256,84070016,US,USA,840,NaN,Central Utah,Utah,US,39.372319,-111.575868,...,51,48,50,54,61,70,75,77,79,81
3257,84070017,US,USA,840,NaN,Southeast Utah,Utah,US,38.996171,-110.701396,...,26,28,28,28,28,29,29,29,29,29
3258,84070018,US,USA,840,NaN,Southwest Utah,Utah,US,37.854472,-111.441876,...,637,655,680,718,739,780,806,827,855,889
3259,84070019,US,USA,840,NaN,TriCounty,Utah,US,40.124915,-109.517442,...,22,22,23,27,27,29,30,30,31,33
3260,84070020,US,USA,840,NaN,Weber-Morgan,Utah,US,41.271160,-111.914512,...,397,408,414,423,439,471,502,511,539,555

In [4]:
locations = jhcounty_cases[["Lat","Long_"]].astype(float)

cases = jhcounty_cases["6/17/2020"].astype(float)

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights = cases,
                                 dissipating=False, max_intensity=100,
                                 point_radius = .2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
low_cases_tx = jhcounty_cases.loc[(jhcounty_cases['Province_State']=='Texas') & (jhcounty_cases['6/17/2020']<10)]
low_cases_tx

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,6/8/2020,6/9/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020
2531,84048007,US,USA,840,48007.0,Aransas,Texas,US,28.105562,-96.999505,...,5,5,5,5,6,6,6,6,7,7
2532,84048009,US,USA,840,48009.0,Archer,Texas,US,33.615700,-98.687546,...,2,3,3,3,3,3,3,3,3,3
2533,84048011,US,USA,840,48011.0,Armstrong,Texas,US,34.965074,-101.357487,...,3,3,3,3,3,2,2,2,2,3
2537,84048019,US,USA,840,48019.0,Bandera,Texas,US,29.746196,-99.245981,...,6,6,6,6,7,7,7,7,7,7
2539,84048023,US,USA,840,48023.0,Baylor,Texas,US,33.616408,-99.213529,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2765,84048475,US,USA,840,48475.0,Ward,Texas,US,31.509996,-103.092791,...,1,2,2,2,4,4,4,4,7,7
2771,84048487,US,USA,840,48487.0,Wilbarger,Texas,US,34.079458,-99.241784,...,7,7,7,7,7,7,7,7,7,7
2775,84048495,US,USA,840,48495.0,Winkler,Texas,US,31.850087,-103.048516,...,3,3,3,3,4,4,4,4,4,4
3190,84080048,US,USA,840,80048.0,Out of TX,Texas,US,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
3242,84090048,US,USA,840,90048.0,Unassigned,Texas,US,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0

In [11]:
hotel_df = pd.DataFrame(low_cases_tx)
hotel_df.reset_index(drop=True, inplace = True)
hotel_df = hotel_df.drop([83,84])
hotel_df = hotel_df[['Admin2','Province_State','Lat','Long_','6/17/2020']]
hotel_df['Hotel Name'] = ''

In [12]:
params = {
    "radius": 2000,
    "types": "lodging",
    "keyword": "hotel",
    "key" : gkey}

#query for lodging/hotels within 2000 meter radius, if no hotel found within these parameters, populating DF with "No Hotel"
for index, row in hotel_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    lat=row['Lat']
    lng=row['Long_']
    
    params["location"] = f"{lat},{lng}"
    
    hotel_query = requests.get(base_url, params=params).json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_query["results"][0]["name"]
    except (KeyError,IndexError):
        print('Missing field/result...populating "No Hotel".')
        hotel_df.loc[index, "Hotel Name"] = "No Hotel"
hotel_df

Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".
Missing field/result...populating "No Hotel".

,Admin2,Province_State,Lat,Long_,6/17/2020,Hotel Name
0,Aransas,Texas,28.105562,-96.999505,7,No Hotel
1,Archer,Texas,33.615700,-98.687546,3,No Hotel
2,Armstrong,Texas,34.965074,-101.357487,3,No Hotel
3,Bandera,Texas,29.746196,-99.245981,7,No Hotel
4,Baylor,Texas,33.616408,-99.213529,1,No Hotel
...,...,...,...,...,...,...
78,Throckmorton,Texas,33.177514,-99.212268,1,No Hotel
79,Upton,Texas,31.368682,-102.042322,1,No Hotel
80,Ward,Texas,31.509996,-103.092791,7,No Hotel
81,Wilbarger,Texas,34.079458,-99.241784,7,No Hotel
82,Winkler,Texas,31.850087,-103.048516,4,Holiday Inn Express Kermit

In [16]:
hotel_df.to_csv('covid hotels.csv')

In [17]:
hotel_df = pd.read_csv('covid hotels.csv')
hotels_df = hotel_df.loc[hotel_df['Hotel Name'] != 'No Hotel']
hotels_df

,Unnamed: 0,Admin2,Province_State,Lat,Long_,6/17/2020,Hotel Name
11,11,Clay,Texas,33.786867,-98.207712,5,Best Western Henrietta Inn & Suites
13,13,Coke,Texas,31.889117,-100.529753,4,Wildcat RV and Paint Creek MH Parks
21,21,Delta,Texas,33.385709,-95.669211,3,The Emma Grace
27,27,Fisher,Texas,32.742813,-100.401930,2,Roby Inn
34,34,Hardeman,Texas,34.289445,-99.746324,4,SureStay Plus Hotel by Best Western Quanah
35,35,Haskell,Texas,33.178236,-99.730374,4,AmeriStay Inn & Suites
38,38,Jack,Texas,33.233772,-98.172835,4,JR'S Chophouse B&B
44,44,Kimble,Texas,30.486789,-99.748565,1,Econo Lodge Junction
50,50,Llano,Texas,30.706450,-98.684753,5,Cabin at Crooked Creek
63,63,Rains,Texas,32.871094,-95.792327,6,Bent Tree Motel
72,72,Somervell,Texas,32.222368,-97.774035,3,Live Oak Bed and Breakfast
82,82,Winkler,Texas,31.850087,-103.048516,4,Holiday Inn Express Kermit

In [18]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>County</dt><dd>{Admin2}</dd>
<dt>Cases</dt><dd>{6/17/2020}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotels_info = [info_box_template.format(**row) for index, row in hotels_df.iterrows()]
locations = hotels_df[["Lat", "Long_"]]

In [19]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotels_info)

# Display figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))